---
title: "Untitled"
author: "Haechan Jung"
date: "2024-12-22"
output: pdf_document
---

```{r message = FALSE, warning=FALSE}
library(alr4)
library(tidyverse)
library(readr)
library(dplyr)
library(dbplyr)
library(DBI)
library(RSQLite)
```
```{r message = FALSE, warning=FALSE}
view_history = read_csv("C:/Users/user/OneDrive/바탕 화면/프로젝트/YouTube-View-History/datasets/YouTube_View_History_Modified.csv", locale = locale(encoding = "EUC-KR"))
```

```{r}
conn = src_memdb()

conn_isolated = conn$con
copy_to(conn, view_history, overwrite = TRUE)
# 가장 많은 영상을 본 채널 목록.csv
df = tbl(conn, sql("SELECT channel_name
                    , COUNT(DISTINCT video_link) AS cnts
                    , channel_link
               FROM view_history
               GROUP BY channel_link
               ORDER BY cnts DESC"))
df
sum(is.na(view_history$viewing_time))
write.csv(df, "C:/Users/user/OneDrive/바탕 화면/프로젝트/YouTube-View-History/datasets/YouTube_Channels.csv")
```
```{r}
for (i in 1:length(view_history$video_link)) {
  if (is.na(view_history$viewing_time[i])) {
    print(view_history$video_link[i])
    print(view_history$video_title[i])
    print(view_history$channel_link[i])
    print(view_history$channel_name[i])
    print(view_history$viewing_time[i])
    print("====================================")
  }
}
```


```{sql connection=conn_isolated}
-- all_cnts = 전체 동영상 수
-- all_distinct_cnts = 시청한 개별적인 동영상 수
SELECT COUNT(link) AS all_cnts
    ,  COUNT(DISTINCT link) as all_distinct_cnts
FROM view_history
```

```{sql connection=conn_isolated}
SELECT channel_name
     , COUNT(DISTINCT link) as cntss
FROM view_history
GROUP BY channel_link
ORDER BY cnts DESC
```
```{r}

```


